<a href="https://colab.research.google.com/github/Karthik5412/News-Categorizer-Nlp-Model/blob/main/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/news model/english_news_dataset.csv')

In [ ]:
df.head(2)

,Headline,Content,News Categories,Date
0,Congress leader Baljinder Singh shot dead at h...,Congress leader Baljinder Singh was shot dead ...,['national'],19-09-2023
1,17-year-old girl preparing for NEET dies by su...,Another NEET aspirant died by suicide in Rajas...,['national'],19-09-2023

In [ ]:
df.shape

(307696, 4)

In [ ]:
df.isna().sum()

Headline           0
Content            0
News Categories    0
Date               0
dtype: int64

In [ ]:
import re

df['News Categories'] = df['News Categories'].apply(lambda x : re.sub(f'[^a-zAz\s]','',x.lower())).str.split(' ')

In [ ]:
df['News Categories'].value_counts()

News Categories
[entertainment]                                                                                  16728
[miscellaneous]                                                                                  13691
[science]                                                                                        12465
[politics, national]                                                                             12165
[sports]                                                                                         11348
                                                                                                 ...
[miscellaneous, world, sports]                                                                       1
[experiment, sports, olympics]                                                                       1
[olympics, national]                                                                                 1
[feelgoodstories, politics, hatke, education, miscellaneous, entertainment, national, travel]        1
[feelgoodstories, hatke, education, miscellaneous, entertainment, national, travel, fashion]         1
Name: count, Length: 1333, dtype: int64

In [ ]:
needed_cols = ['business', 'world', 'entertainment', 'politics', 'automobile', 'national','science', 'sports','education',
               'miscellaneous','startup','healthfitness','technology', 'travel','fasion']

def refeared_final (x):
    if x[0] in needed_cols:
        return x[0]
    else :
        for i in x:
            if i in (needed_cols) :
                return i
        else :
            return i


df['Final cat'] = df['News Categories'].apply(refeared_final)
df['Final cat'].value_counts()

Final cat
business         38119
world            36164
entertainment    29828
politics         28656
sports           22025
automobile       21903
national         21582
miscellaneous    20838
science          20721
education        20309
startup          13646
healthfitness    10612
technology        8738
travel            8659
fashion           5896
Name: count, dtype: int64

In [ ]:
df[df['Final cat'] == 'miscellaneous']

,Headline,Content,News Categories,Date,Final cat
1437,Thailand PM welcomes 10 millionth visitor of 2...,Thailand PM Prayut Chan-o-cha welcomed the cou...,"[miscellaneous, travel]",19-09-2023,miscellaneous
1530,Pic of Kerala Mayor Arya Rajendran working whi...,A picture of Thiruvananthapuram Mayor Arya Raj...,[miscellaneous],19-09-2023,miscellaneous
1531,2 US models found dead in their luxury apartme...,Two models living in the same area were found ...,[miscellaneous],19-09-2023,miscellaneous
1532,Dinosaur skeleton may sell for up to ₹11 crore...,"An unusually well-preserved dinosaur skeleton,...",[miscellaneous],19-09-2023,miscellaneous
1533,Pink pigeon spotted in UK; pics go viral,A pink pigeon was spotted roaming on streets i...,[miscellaneous],19-09-2023,miscellaneous
...,...,...,...,...,...
307401,"Bella Hadid wears a keffiyeh dress, flaunts he...","On Thursday, supermodel Bella Hadid was snappe...","[hatke, miscellaneous, lifestyle, fashion]",2024-08-26,miscellaneous
307522,Video: Teacher dancing with transgender dies d...,An environment of fear has gripped the entire ...,"[hatke, miscellaneous, education]",2024-08-26,miscellaneous
307525,"Sensex, Nifty crash amid pressure on global ma...",Equity market benchmark indices Sensex and Nif...,"[miscellaneous, education]",2024-08-26,miscellaneous
307555,Jabalpur school punishes 300 students for 5-mi...,A Convent school in Jabalpur of Madhya Pradesh...,"[miscellaneous, education]",2024-08-26,miscellaneous
307648,Mumbai: BMC resident doctors continue strike; ...,A day after a female resident doctor was assau...,"[hatke, miscellaneous, national, healthfitness]",2024-08-26,miscellaneous