<a href="https://colab.research.google.com/github/Karthik5412/News-Categorizer-Nlp-Model/blob/main/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('/content/drive/MyDrive/news model/english_news_dataset.csv')

In [5]:
df.head(2)

                                            Headline  ...        Date
0  Congress leader Baljinder Singh shot dead at h...  ...  19-09-2023
1  17-year-old girl preparing for NEET dies by su...  ...  19-09-2023

[2 rows x 4 columns]

In [6]:
df.shape

(307696, 4)

In [7]:
df.isna().sum()

Headline           0
Content            0
News Categories    0
Date               0
dtype: int64

In [8]:
import re

df['News Categories'] = df['News Categories'].apply(lambda x : re.sub(f'[^a-zAz\s]','',x.lower())).str.split(' ')

In [9]:
df['News Categories'].value_counts()

News Categories
[entertainment]                                                                                  16728
[miscellaneous]                                                                                  13691
[science]                                                                                        12465
[politics, national]                                                                             12165
[sports]                                                                                         11348
                                                                                                 ...
[miscellaneous, world, sports]                                                                       1
[experiment, sports, olympics]                                                                       1
[olympics, national]                                                                                 1
[feelgoodstories, politics, hatke, education, miscellaneous, entertainment, national, travel]        1
[feelgoodstories, hatke, education, miscellaneous, entertainment, national, travel, fashion]         1
Name: count, Length: 1333, dtype: int64

In [10]:
needed_cols = ['business', 'world', 'entertainment', 'politics', 'automobile', 'national','science', 'sports','education',
               'startup','healthfitness','technology', 'travel','fasion']

def refeared_final (x):
    if x[0] in needed_cols:
        return x[0]
    else :
        for i in x:
            if i in (needed_cols) :
                return i
        else :
            return i


df['Final cat'] = df['News Categories'].apply(refeared_final)
df['Final cat'].value_counts()

Final cat
business          38412
world             36794
entertainment     30452
politics          28656
national          23350
sports            22125
automobile        21903
science           20875
education         20410
miscellaneous     14718
startup           13689
healthfitness     11145
travel             9687
technology         8884
fashion            6090
lifestyle           491
odiworldcup           4
experiment            4
ipl                   2
olympics              2
finance               2
israelhamaswar        1
Name: count, dtype: int64

In [11]:
df[df['Final cat'] == 'miscellaneous']

                                                 Headline  ...      Final cat
1530    Pic of Kerala Mayor Arya Rajendran working whi...  ...  miscellaneous
1531    2 US models found dead in their luxury apartme...  ...  miscellaneous
1532    Dinosaur skeleton may sell for up to ₹11 crore...  ...  miscellaneous
1533             Pink pigeon spotted in UK; pics go viral  ...  miscellaneous
1534    Baby born with 14 fingers & 12 toes in Rajasth...  ...  miscellaneous
...                                                   ...  ...            ...
307269  Drunk man bites off part of father's thumb aft...  ...  miscellaneous
307271  Snake seen with its head stuck in beer can in ...  ...  miscellaneous
307276  What are the tips to prevent memory decline wi...  ...  miscellaneous
307278  What are benefits of drinking fennel seed wate...  ...  miscellaneous
307282                 What is mono diet?                  ...  miscellaneous

[14718 rows x 5 columns]

In [12]:
# concatinating columns
df['Description'] = df['Headline'] + ' ' + df['Content']
df.head()

                                            Headline  ...                                        Description
0  Congress leader Baljinder Singh shot dead at h...  ...  Congress leader Baljinder Singh shot dead at h...
1  17-year-old girl preparing for NEET dies by su...  ...  17-year-old girl preparing for NEET dies by su...
2  Hampers to welcome MPs in new Parliament tomor...  ...  Hampers to welcome MPs in new Parliament tomor...
3  Only 10% women lawmakers in RS, while only 14%...  ...  Only 10% women lawmakers in RS, while only 14%...
4  Ganesh temple decorated with notes, coins wort...  ...  Ganesh temple decorated with notes, coins wort...

[5 rows x 6 columns]

In [13]:
# Droping unwanted columns
df = df.drop(columns= ['News Categories', 'Date', 'Headline', 'Content'])
df = df[df['Final cat'] != 'miscellaneous']

df = df[['Description', 'Final cat']]
df.head()

                                         Description Final cat
0  Congress leader Baljinder Singh shot dead at h...  national
1  17-year-old girl preparing for NEET dies by su...  national
2  Hampers to welcome MPs in new Parliament tomor...  national
3  Only 10% women lawmakers in RS, while only 14%...  national
4  Ganesh temple decorated with notes, coins wort...  national

In [14]:
df['Final cat'].value_counts()

Final cat
business          38412
world             36794
entertainment     30452
politics          28656
national          23350
sports            22125
automobile        21903
science           20875
education         20410
startup           13689
healthfitness     11145
travel             9687
technology         8884
fashion            6090
lifestyle           491
odiworldcup           4
experiment            4
ipl                   2
olympics              2
finance               2
israelhamaswar        1
Name: count, dtype: int64

In [15]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [16]:
stopwords = set(stopwords.words('english'))
lemetizer = WordNetLemmatizer()

In [17]:
df['Description'][12]

'14-year-old girl dies, several others hospitalised after eating shawarma in TN A 14-year-old schoolgirl died after eating chicken shawarma bought from a hotel in Tamil Nadu. Thirteen medical college students were also reportedly hospitalised on the same night after eating shawarma from the same hotel. Namakkal Collector S Uma ordered the destruction of all food items and issued a notice to the hotel, which was then sealed.'

In [18]:
# droping punctuations and numbers after converting it to lower case

import re


def refining(x):
   data = re.sub(r'[^a-zA-z\s]','',x.lower())

   data = data.split()

   cleaned = [w for w in data if w not in stopwords]

   cleaned = [lemetizer.lemmatize(w) for w in cleaned]


   return " ".join(cleaned)

df['Description'] = df['Description'].apply(refining)

df['Description'][12]

'yearold girl dy several others hospitalised eating shawarma tn yearold schoolgirl died eating chicken shawarma bought hotel tamil nadu thirteen medical college student also reportedly hospitalised night eating shawarma hotel namakkal collector uma ordered destruction food item issued notice hotel sealed'

In [31]:
from sklearn.feature_extraction.text import  TfidfVectorizer
tfidf = TfidfVectorizer(max_features= 1000, ngram_range= (1,2), sublinear_tf= True)

In [32]:
word_matrix = tfidf.fit_transform(df['Description'])

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

labels = le.fit_transform(df['Final cat'])

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression

In [35]:
x_train, x_test, y_train, y_test = train_test_split(word_matrix, labels, test_size= 0.3, random_state = 42)

In [36]:
clf = LinearSVC(class_weight='balanced')

clf.fit(x_train, y_train)

LinearSVC(class_weight='balanced')

In [37]:
pred = clf.predict(x_test)
pred

array([ 0,  3, 16, ..., 11, 20, 14])

In [38]:
y_test

array([ 0,  3, 16, ..., 14, 20, 14])

In [39]:
from sklearn.metrics import accuracy_score, classification_report

print(accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

0.7820215259289599
              precision    recall  f1-score   support

           0       0.88      0.95      0.91      6613
           1       0.79      0.66      0.72     11474
           2       0.82      0.89      0.85      6048
           3       0.86      0.86      0.86      9135
           4       1.00      1.00      1.00         1
           5       0.71      0.90      0.79      1843
           6       1.00      1.00      1.00         1
           7       0.63      0.80      0.71      3365
           8       1.00      1.00      1.00         1
          10       0.33      0.81      0.47       149
          11       0.71      0.63      0.67      7119
          12       1.00      1.00      1.00         1
          13       0.00      0.00      0.00         2
          14       0.82      0.84      0.83      8378
          15       0.80      0.86      0.83      6192
          16       0.90      0.90      0.90      6721
          17       0.62      0.71      0.66      4172
          18       0.55      0.73      0.63      2609
          19       0.76      0.90      0.82      2955
          20       0.80      0.60      0.69     11115

    accuracy                           0.78     87894
   macro avg       0.75      0.80      0.77     87894
weighted avg       0.79      0.78      0.78     87894